package test;

public class ExceptionTest {

	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		int nVar = 0;
		int nResult;

		nResult = 7 / nVar;
		System.out.println(nResult);
		
//		try
//		{
//			nResult = 7 / nVar;
//		}catch(ArithmeticException e) {
//			System.out.println("failed");
//		}
	}

}
